version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app-sisconced
    volumes:
      - app-dev:/var/www/sisconced
      - php-fpm-sock:/var/run/php
    environment:
      - "DB_HOST=pgsql"  
      - "DB_PORT=5432"  
      - "DB_DATABASE=sisconced"
      - "DB_USERNAME=desarrollador"
      - "DB_PASSWORD=mysecretpassword"
    networks:
      - app-network
    ports:
      - "80:80"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx-sisconced
    volumes:
      - app-dev:/var/www/sisconced
      - php-fpm-sock:/var/run/php
      - ./certs:/etc/nginx/certs
    ports:
      - "8081:80"
      - "443:443"
    networks:
      - app-network

  postgresdb:
    image: postgres:latest
    container_name: db-sisconced
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - postgresdata:/var/lib/postgresql/data
    command: ["/bin/bash", "./dbsetup.sh"]
      
  servercache:
    image: redis:latest
    container_name: redis-sisconced
    ports:
      - 6379:6379
    networks:
      - app-network
    volumes:
      - redisdata:/redis/data

volumes:
  app-dev:
  php-fpm-sock:
  redisdata:
  postgresdata:
  pgadmindata:
  certs:
  
networks:
  app-network:
    driver: bridge
  