version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app-sisconced
    volumes:
      - app-dev:/var/www/sisconced
      - php-fpm-sock:/var/run/php/php8.2-fpm.sock
      - ./certs:/etc/nginx/certs
    networks:
      - app-network
    ports:
      - "8080:80"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx-sisconced
    volumes:
      - app-dev:/var/www/sisconced
      - php-fpm-sock:/var/run/php/php8.2-fpm.sock
      - ./certs:/etc/nginx/certs
    ports:
      - "8082:80"
      - "443:443"
    networks:
      - app-network
    
  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    container_name: proxy-sisconced
    ports:
      - "80:80"
    networks:
      - app-network

  postgresdb:
    image: postgres:latest
    container_name: db-sisconced
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - postgresdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8090:80
    networks:
      - app-network
    depends_on:
      - postgresdb
    volumes:
      - postgresdata:/var/lib/postgresql/data
      
  servercache:
    image: redis:latest
    container_name: redis-sisconced
    ports:
      - 6379:6379
    networks:
      - app-network
    volumes:
      - redisdata:/redis/data

volumes:
  app-dev:
  php-fpm-sock:
  redisdata:
  postgresdata:
  
networks:
  app-network:
    driver: bridge
  